server.port: 8090
spring:
  main.allow-bean-definition-overriding: true
  datasource:
    ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: juega100
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.format_sql: true
    show-sql: true

  profiles:
    active: develop
logging:
  level:
    org.springframework: ERROR
    com.io.one.health: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: money-exchange-service.log
